### ISSUE TITLE
Problem regarding estimation accuracy in Foot Region

### ISSUE THREAD

**Issue by Marlod390** [caizhongang/SMPLer-X#45] opened 2024-01-18 20:59 UTC
Hi, I ran the project on other videos and it worked generally well. But I observed some differences between the pose estimation output and the actual human pose, especially in the foot area. The attached image shows a clear divergence, where the estimated pose points are not aligned with the physical position of the foot:

![000001](https://github.com/caizhongang/SMPLer-X/assets/67206431/beaaf999-1442-47c1-bf0a-459ee4c34470)
![000200](https://github.com/caizhongang/SMPLer-X/assets/67206431/0da9945a-9ef2-4779-a293-a3761d43f582)

I tried models s to h and the same problem occurred in all models. Can you give your opinion on this matter? Is this a known issue or could you recommend any method to improve the performance?

Thanks in advance.

**Comment by Wei-Chen-hub** [comment] 2024-02-01 09:04
In my opinion, it looks like a projection error (i.e. scale), the knee & leg also seems to be smaller that the real size.

Please upload the photo so that i can check it out from my side.

**Comment by Marlod390** [comment] 2024-02-01 09:50
Thanks for your reply. Here is the original video:
https://github.com/caizhongang/SMPLer-X/assets/67206431/96a1471e-b17d-401c-bf91-3817cfba144c

**Comment by Wei-Chen-hub** [comment] 2024-04-03 08:50
Apologize for the late response, I have done a throughly check, and found a bug in 3DPW dataset loader. There was a mismatch of bbox size (1 vs. 1.25) during image preprocessing, therefore 2d keypoints was smaller that actual. The affect is that model would yeild smaller person on 3DPW-like data.

![3219](https://github.com/caizhongang/SMPLer-X/assets/77597327/9e646459-ec4b-46c7-b1b6-4f8deba0758e)


We have fixed this issue and re-done the training. With updated model, the problem is solved.
<img width="1370" alt="smplerx_issue45_fix" src="https://github.com/caizhongang/SMPLer-X/assets/77597327/c7c38c6a-0ddf-4d7c-a265-b9fa91629d81">

Please try the updated model, hope this reply would help.

**Comment by Wei-Chen-hub** [comment] 2024-04-03 09:07
I will close this issue for now, if you encounter any other situations, feel free to raise a new issue.

**Closed by Wei-Chen-hub** 2024-04-03 09:07 UTC
